CREATE SCHEMA popin;

CREATE TABLE "popin"."user" (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    register_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);